"""Centralized Telegram command names with `company_` prefix."""

CMD_START = "company_start"
CMD_CREATE_COMPANY = "company_create"
CMD_COMPANY = "company"
CMD_LIST_COMPANY = "company_list"
CMD_RANK_COMPANY = "company_rank"
CMD_BATTLE = "company_battle"
CMD_COOPERATE = "company_cooperate"
CMD_NEW_PRODUCT = "cp_new_product"
CMD_MEMBER = "company_member"
CMD_DISSOLVE = "company_dissolve"
CMD_QUEST = "company_quest"
CMD_HELP = "company_help"
CMD_ADMIN = "company_admin"
CMD_GIVE_MONEY = "company_give"
CMD_WELFARE = "company_welfare"
CMD_CLEAR_PRODUCT = "company_clear"
CMD_CLEANUP = "company_cleanup"
CMD_MAKEUP = "company_makeup"
CMD_CANCEL = "company_cancel"
