"""Centralized Telegram command names with `cp_` prefix."""

CMD_START = "cp_start"
CMD_CREATE_COMPANY = "cp_create"
CMD_COMPANY = "cp"
CMD_LIST_COMPANY = "cp_list"
CMD_RANK_COMPANY = "cp_rank"
CMD_BATTLE = "cp_battle"
CMD_COOPERATE = "cp_cooperate"
CMD_NEW_PRODUCT = "cp_new_product"
<<<<<<< HEAD
CMD_DEMON = "cp_demon"
CMD_MEMBER = "company_member"
CMD_INVEST = "company_invest"
CMD_DIVIDEND = "company_dividend"
CMD_TRANSFER = "company_transfer"
CMD_EXCHANGE = "company_exchange"
CMD_LOG = "company_log"
CMD_DISSOLVE = "company_dissolve"
CMD_QUEST = "company_quest"
CMD_HELP = "company_help"
CMD_ADMIN = "company_admin"
CMD_GIVE_MONEY = "company_give"
CMD_WELFARE = "company_welfare"
CMD_CLEAR_PRODUCT = "company_clear"
CMD_CLEANUP = "company_cleanup"
CMD_MAKEUP = "company_makeup"
CMD_CANCEL = "company_cancel"
CMD_CHECKIN = "company_checkin"
CMD_REDPACKET = "company_redpacket"
CMD_RENAME = "company_rename"
CMD_BLOCK = "block"
CMD_UNBLOCK = "unblock"
=======
CMD_MEMBER = "cp_member"
CMD_INVEST = "cp_invest"
CMD_DIVIDEND = "cp_dividend"
CMD_TRANSFER = "cp_transfer"
CMD_EXCHANGE = "cp_exchange"
CMD_LOG = "cp_log"
CMD_DISSOLVE = "cp_dissolve"
CMD_QUEST = "cp_quest"
CMD_HELP = "cp_help"
CMD_GIVE_MONEY = "cp_give"
CMD_WELFARE = "cp_welfare"
CMD_CLEANUP = "cp_cleanup"
CMD_MAKEUP = "cp_makeup"
CMD_MAINTAIN = "cp_maintain"
CMD_COMPENSATE = "cp_compensate"
CMD_CANCEL = "cp_cancel"
CMD_CHECKIN = "cp_checkin"
CMD_REDPACKET = "cp_redpacket"
CMD_RENAME = "cp_rename"
>>>>>>> bbe157905e8d819c6fa6d4da5d4964ccaf975115
